project:
  type: website
  output-dir: _site

website:
  title: "My Personal Blog"
  site-url: https://gnart33.github.io
  repo-url: https://github.com/gnart33/gnart33.github.io
  repo-actions: [edit, issue]
  page-navigation: true
  search: true
  page-footer:
    left: |
      Built with [Quarto](https://quarto.org)
    center:
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: blog/index.qmd
    right:
      - icon: github
        href: https://github.com/gnart33/gnart33.github.io
        aria-label: GitHub Repository
  navbar:
    background: light
    search: true
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/gnart33/gnart33.github.io
        aria-label: GitHub Repository
  # sidebar:
  #   style: "floating"
  #   contents:
  #     - section: "Blog"
  #       contents:
  #         - blog/index.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    highlight-style: github
    code-fold: true
    code-tools: true
    fig-responsive: true
    fig-format: retina
    fig-dpi: 144
    fig-asp: 1.618
    fig-width: 8
    fig-height: 5
    fig-align: center
    fig-pos: H
    fig-cap-location: bottom
    fig-subcap-location: bottom
    fig-link: false
    fig-alt: null
    fig-env: figure
    fig-scap: null
    fig-lp: null
    fig-float: true
    fig-float-placement: H
    fig-float-reference: fig
    fig-float-caption: true
    fig-float-caption-location: bottom
    fig-float-caption-style: null
    fig-float-caption-sep: ": "
    fig-float-caption-prefix: "Figure "
    fig-float-caption-suffix: "."
    fig-float-caption-prefix-singular: "Figure "
    fig-float-caption-prefix-plural: "Figures "
    fig-float-caption-sep-singular: ": "
    fig-float-caption-sep-plural: ": "
    fig-float-caption-suffix-singular: "."
    fig-float-caption-suffix-plural: "."
    fig-float-caption-style-singular: null
    fig-float-caption-style-plural: null
    